#pragma once
#define Splash_State_BG_Filepath "Resources/splashstate.png"
#define Main_Menu_State_BG_Filepath "Resources/bg-menu.png"
#define Game_State_BG_Filepath "Resources/bg-play.png"
#define Tutorial_BG "Resources/tutorial.png"
#define Word_Bank "res/WordBank.txt"
#define Main_Menu_Font_Filepath "Resources/Fonts/LEMONMILK-Regular.otf"
#define Splash_Time 2
#define Shark_Speed -30
#define Game_Over_Time 3
#define Shark_Death_Timer 0.5
#define Player_Sprite_Texture_Filepath "Resources/texture/diver.png"
#define Game_Over_Texture_Filepath "Resources/GameOver.jpg"
#define Enemy_1_Sprite_Texture_Filepath "Resources/texture/hiu1.png"
#define Enemy_2_Sprite_Texture_Filepath "Resources/texture/hiu2.png"
#define Bone_1 "Resources/texture/bone-shark.png"
#define Bone_2 "Resources/texture/bone-shark2.png"
#define Pause_Screen_Filepath "Resources/PauseScreen.png"
#define Main_Menu_Music_Filepath "Resources/Sound/MainMenu.ogg"
#define Game_Music "Resources/Sound/GameState.ogg"
#define Game_Over_Music "Resources/Sound/GameOver.ogg"
#define Player_Dies "Resources/Sound/playerdies.ogg"
#define Shark_Dies "Resources/Sound/sharkdies.ogg"
#define Shark_Hit "Resources/Sound/sharkhurt.ogg"
#define Wrong "Resources/Sound/wrong.ogg"
#define Highscore_Filepath "res/highscore.txt"