#pragma once
#define Splash_State_BG_Filepath "Resources/SplashState.png"
#define Main_Menu_State_BG_Filepath "Resources/MainMenu.jpg"
#define Game_Menu_State_BG_Filepath "Resources/GameState.png"
#define Main_Menu_Font_Filepath "Resources/Fonts/SeasideResortNF.ttf"
#define Splash_Time 2
#define Fish_Time 25
#define Food_Interval 15
#define Game_Over_Time 1.5
#define Player_Sprite_Texture_Filepath "Resources/Player.png"
#define Game_Over_Texture_Filepath "Resources/GameOver.jpg"
#define Enemy_1_Sprite_Texture_Filepath "Resources/Enemy1.png"
#define Enemy_2_Sprite_Texture_Filepath "Resources/Enemy2.png"
#define Enemy_3_Sprite_Texture_Filepath "Resources/Enemy3.png"
#define Enemy_4_Sprite_Texture_Filepath "Resources/Enemy4.png"
#define Food_Texture_Filepath "Resources/Food.png"
#define Pause_Screen_Filepath "Resources/PauseScreen.png"
#define Main_Menu_Music_Filepath "Resources/Sound/MainMenu.ogg"
#define Game_State_Music_Filepath "Resources/Sound/GameState.ogg"
#define Game_Over_Music_Filepath "Resources/Sound/GameOver.ogg"
#define Bite_Sound_Filepath "Resources/Sound/Bite.ogg"
#define page_1_Tutorial_Filepath "Resources/Tutorial1.png"
#define page_2_Tutorial_Filepath "Resources/Tutorial2.png"